// Generated by scripts/import-story-audio.mjs and scripts/import-transcript-cues.mjs.
// Full-story sources stay global; mapped transcript cues drive paragraph highlighting.
import { transcriptCues, transcriptSceneAnchors } from './transcript-cues.js';

export const storyAudio = {
  "en": {
    "status": "available",
    "src": "assets/audio/en/story.mp3",
    "duration": 403.507415,
    "cues": transcriptCues.en,
    "sceneAnchors": transcriptSceneAnchors.en
  },
  "id": {
    "status": "available",
    "src": "assets/audio/id/story.mp3",
    "duration": 403.507415,
    "cues": transcriptCues.id,
    "sceneAnchors": transcriptSceneAnchors.id
  },
  "jv": {
    "status": "available",
    "src": "assets/audio/jv/story.mp3",
    "duration": 524.507415,
    "cues": transcriptCues.jv,
    "sceneAnchors": transcriptSceneAnchors.jv
  }
};
